config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  
  get 'homes/index' => 'homes#index'
  
  post 'homes/fake_news' => 'homes#fake_news'
  
  get 'homes/index_json' => 'homes#index_json'

  resources :all_notices
  
  get 'homes/index'
  
  get 'users/page/:id' => 'users#page'
  
  # User 리스트를 json으로 받아옴.
  get 'users/user_list'
  
  #쪽지
  get '/users/message'
  delete '/users/message/:id' => 'messages#destroy'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  resources :messages, only: [:hide_message] do
    member do
      put "hide_message", to: "messages#hide_message"
      put "hide_message_their", to: "messages#hide_message_their"
    end
  end
  
  #검색 결과
  get 'searches/index' => 'searches#index'
  get 'homes/news_search' => 'homes#news_search'
  
  #알림 : 전체 삭제
  get '/new_notifications/read_all' => 'new_notifications#read_all'
  #알림
  resources :new_notifications
  
  resources :comments, only: [:create, :destroy, :edit, :update] do
    member do
      put "like", to:    "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end
  
  resources :posts
  
  resources :bulletins do
    # 해시태그
    get 'posts/hashtag/:name', to: 'posts#hashtags'
    resources :posts do
      post "/restore", to: "posts#restore"
      member do
        put "like", to:    "posts#upvote"
        put "dislike", to: "posts#downvote"
      end
    end
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    has_many :messages
    belongs_to :sender, foreign_key: :sender_id, class_name: User
    belongs_to :recipient, foreign_key: :recipient_id, class_name: User
    
    validates :sender_id, uniqueness: { scope: :recipient_id }
    
    scope :between, -> (sender_id, recipient_id) do
        where(sender_id: sender_id, recipient_id: recipient_id).or(where(sender_id: recipient_id, recipient_id: sender_id))
    end
    
    def self.get(sender_id, recipient_id)
        conversation = between(sender_id, recipient_id).first
        return conversation if conversation.present?
        create(sender_id: sender_id, recipient_id: recipient_id)
    end
    
    def opposed_user(user)
        user == recipient ? sender : recipient
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    def create
        @conversation = Conversation.get(current_user.id, params[:user_id])
        add_to_conversations unless conversated?
        respond_to do |format|
            format.js
        end
    end
    
    def close
        @conversation = Conversation.find(params[:id])
        session[:conversations].delete(@conversation.id)
        
        respond_to do |format|
            format.js
        end
    end
    
    private
    
    def add_to_conversations
        session[:conversations] ||= []
        session[:conversations] << @conversation.id
    end
    
    def conversated?
        session[:conversations].include?(@conversation.id)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<li class="conversation_list">
    <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
        <div class="panel-heading">
            <% if conversation.opposed_user(user) != nil %>
                <%= link_to "<div>#{conversation.opposed_user(user).nickname}</div>".html_safe, '', class: 'toggle-window', style: "text-decoration: none" %>
            <% else %>
                <%= link_to "알 수 없음", '', class: 'toggle-window', style: "text-decoration: none; color: #777777; font-weight: bold;" %>
            <% end %>
            <%= link_to " ", close_conversation_path(conversation), class: "fas fa-times", style: "float: right; margin-top: -18px; color: #8e8e8e; text-decoration: none", remote: true, method: :post %>
        </div>
        
        <div class="panel-body" style="display: visible;">
            <div class="messages-list" style="margin-top: 20px">
                <ul>
                    <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
                </ul>
            </div>
            <% if conversation.recipient != nil %>
                <%= form_for [conversation, conversation.messages.new], remote: true do |f| %>
                    <div class="row" style="margin-top: 10px">
                        <div class="col-9 col-sm-10 col-md-10"><%= f.text_area :body, class: "form-control" %></div>
                        <div class="col-3 col-sm-2 col-md-2"><%= f.submit "전송", class: "btn btn-success" %></div>
                    </div>
                <% end %>
            <% end %>
            <hr/>
        </div>
    </div>
</li>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
    <%= render message, user: user %>
<% end %>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
 
if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}
 
conversation.find('.panel-body').show();
 
var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);