config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  
  get 'homes/index' => 'homes#index'
  
  post 'homes/fake_news' => 'homes#fake_news'
  
  get 'homes/index_json' => 'homes#index_json'

  resources :all_notices
  
  get 'homes/index'
  
  get 'users/page/:id' => 'users#page'
  
  # User 리스트를 json으로 받아옴.
  get 'users/user_list'
  
  #쪽지
  get '/users/message'
  delete '/users/message/:id' => 'messages#destroy'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  resources :messages, only: [:hide_message] do
    member do
      put "hide_message", to: "messages#hide_message"
      put "hide_message_their", to: "messages#hide_message_their"
    end
  end
  
  #검색 결과
  get 'searches/index' => 'searches#index'
  get 'homes/news_search' => 'homes#news_search'
  
  #알림 : 전체 삭제
  get '/new_notifications/read_all' => 'new_notifications#read_all'
  #알림
  resources :new_notifications
  
  resources :comments, only: [:create, :destroy, :edit, :update] do
    member do
      put "like", to:    "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end
  
  resources :posts
  
  resources :bulletins do
    # 해시태그
    get 'posts/hashtag/:name', to: 'posts#hashtags'
    resources :posts do
      post "/restore", to: "posts#restore"
      member do
        put "like", to:    "posts#upvote"
        put "dislike", to: "posts#downvote"
      end
    end
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @option = params[:option]
    if (@option == "1")
      @searches = eval(params[:bulletin]).where('created_at >= :years_ago', :years_ago => Time.now - 1.years).where("title like ?", "%#{params[:search_text]}%").order("created_at DESC").page(params[:page]).per(10)
    elsif (@option == "2")
      @searches = eval(params[:bulletin]).where('created_at >= :years_ago', :years_ago => Time.now - 1.years).where("content like ?", "%#{params[:search_text]}%").order("created_at DESC").page(params[:page]).per(10)
    elsif (@option == "3")
      @searches = eval(params[:bulletin]).where('created_at >= :years_ago', :years_ago => Time.now - 1.years).where("title like ?", "%#{params[:search_text]}%").order("created_at DESC").page(params[:page]).per(10).or(eval(params[:bulletin]).where('created_at >= :years_ago', :years_ago => Time.now - 1.years).where("content like ?", "%#{params[:search_text]}%")).order("created_at DESC").page(params[:page]).per(10)
    elsif (@option == "4")
      @searches = eval(params[:bulletin]).where('created_at >= :years_ago', :years_ago => Time.now - 1.years).where("user_nickname like ?", "%#{params[:search_text]}%").order("created_at DESC").page(params[:page]).per(10)
    end
    @location = params[:bulletin]
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index/_mobile.html.erb
<div style="margin-top: 40px;">
    <% if @searches.empty? %>
        <div align="center">
            <h4  style="margin-top: 80px"><i class="fas fa-chalkboard-teacher"></i> 검색결과가 없습니다.</h4>
            <h7><%= link_to " 돌아가기", request.referrer, class: "fas fa-undo" %></h7>
        </div>
    <% else %>
        <% @searches.each do |x| %>
            <div style="padding-top: 0px;">
                <% if @location == "Post" %>
                    <%= link_to bulletin_post_path(x.bulletin, x), style: "color: black; text-decoration: none" do %>
                        <div class="col-12 col-sm-12 col-md-12"><span style="font-size: 20px; border-bottom: 2px solid #18d26e; padding-bottom: 5px; color: #18d26e; font-weight: bold;"><%= x.bulletin.title %></span></div>
                        <div class="col-12 col-sm-12" style="margin-top: 20px"><h5 style="font-weight: bold;"><%= x.title.truncate(15, omission: '...') %></h5></div>
                        <div class="col-12 col-sm-12"><%= content_tag(:span, truncate( raw( sanitize(x.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 25, :omission => "..."), class: "etc") %></div>
                        <div style="padding-top: 10px; padding-bottom: 20px; padding-right: 20px;">
                            <small style="float: right;">
                                <%= x.user != nil ? x.user.nickname.truncate(10, omission: '...') : x.user_nickname.truncate(10, omission: '...') %>
                                <span style="margin-left: 5px; margin-right: 5px">|</span>
                                <%= x.created_at.in_time_zone("Asia/Seoul").strftime('%Y-%m-%d %H:%M') %>
                                <span style="margin-left: 5px; margin-right: 5px">|</span>
                                <i class="far fa-comment-dots"></i> <%= x.comment_threads.count %>
                            </small>
                        </div>
                    <% end %>
                <% else %>
                    <%= link_to x, style: "color: black; text-decoration: none" do %>
                        <div class="col-12 col-sm-12 col-md-12"><span style="font-size: 20px; border-bottom: 2px solid #18d26e; padding-bottom: 5px; color: #18d26e; font-weight: bold;">공지사항</span></div>
                        <div class="col-md-12" style="margin-top: 20px"><h5 style="font-weight: bold;"><%= x.title.truncate(15, omission: '...') %></h5></div>
                        <div class="col-md-12"><%= content_tag(:span, truncate( raw( sanitize(x.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 25, :omission => "..."), class: "etc") %></div>
                        <div style="padding-top: 10px; padding-bottom: 20px; padding-right: 20px;">
                            <small style="float: right;">
                                <%= x.user != nil ? x.user.nickname.truncate(10, omission: '...') : x.user_nickname.truncate(10, omission: '...') %>
                                <span style="margin-left: 5px; margin-right: 5px">|</span>
                                <%= x.created_at.in_time_zone("Asia/Seoul").strftime('%Y-%m-%d %H:%M') %>
                                <span style="margin-left: 5px; margin-right: 5px">|</span>
                                <i class="far fa-comment-dots"></i> <%= x.comment_threads.count %>
                            </small>
                        </div>
                    <% end %>
                <% end %>
            </div>
            <hr/>
        <% end %>
    <% end %>
</div>

app/views/searches/index/_pc.html.erb
<div class="container" style="margin-top: 40px;">
    <% if @searches.empty? %>
        <div align="center">
            <h2 style="margin-top: 150px"><i class="fas fa-chalkboard-teacher"></i> 검색결과가 없습니다.</h2>
            <h7><%= link_to " 돌아가기", request.referrer, class: "fas fa-undo" %></h7>
        </div>
    <% else %>
        <% @searches.each do |x| %>
            <div style="padding: 40px">
                <% if @location == "Post" %>
                    <%= link_to bulletin_post_path(x.bulletin, x), style: "color: black; text-decoration: none" do %>
                        <div class="col-12 col-sm-12 col-md-12"><span style="font-size: 20px; border-bottom: 2px solid #18d26e; padding-bottom: 5px; color: #18d26e; font-weight: bold;"><%= x.bulletin.title %></span></div>
                        <div class="col-md-12" style="margin-top: 40px"><h5 style="font-weight: bold;"><%= x.title.truncate(20, omission: '...') %></h5></div>
                        <div class="col-md-12">
                            <%= content_tag(:span, truncate( raw( sanitize(x.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 70, :omission => "..."), class: "etc") %>
                        </div>
                        <small style="float: right; margin-top: 20px;">
                            <%= x.user != nil ? x.user.nickname.truncate(15, omission: '...') : x.user_nickname.truncate(15, omission: '...') %>
                            <span style="margin-left: 5px; margin-right: 5px">|</span>
                            <%= x.created_at.in_time_zone("Asia/Seoul").strftime('%Y-%m-%d %H:%M') %>
                            <span style="margin-left: 5px; margin-right: 5px">|</span>
                            <i class="far fa-comment-dots"></i> <%= x.comment_threads.count %>
                        </small>
                    <% end %>
                <% else %>
                    <%= link_to x, style: "color: black; text-decoration: none" do %>
                        <div class="col-12 col-sm-12 col-md-12"><span style="font-size: 20px; border-bottom: 2px solid #18d26e; padding-bottom: 5px; color: #18d26e; font-weight: bold;">공지사항</span></div>
                        <div class="col-md-12" style="margin-top: 40px"><h5 style="font-weight: bold;"><%= x.title.truncate(20, omission: '...') %></h5></div>
                        <div class="col-md-12">
                            <%= content_tag(:span, truncate( raw( sanitize(x.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 70, :omission => "..."), class: "etc") %>
                        </div>
                        <small style="float: right; margin-top: 20px;">
                            <%= x.user != nil ? x.user.nickname.truncate(12, omission: '...') : x.user_nickname.truncate(12, omission: '...') %>
                            <span style="margin-left: 5px; margin-right: 5px">|</span>
                            <%= x.created_at.in_time_zone("Asia/Seoul").strftime('%Y-%m-%d %H:%M') %>
                            <span style="margin-left: 5px; margin-right: 5px">|</span>
                            <i class="far fa-comment-dots"></i> <%= x.comment_threads.count %>
                        </small>
                    <% end %>
                <% end %>
            </div>
            <hr/>
        <% end %>
    <% end %>
</div>