config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  
  get 'homes/index' => 'homes#index'
  
  post 'homes/fake_news' => 'homes#fake_news'
  
  get 'homes/index_json' => 'homes#index_json'

  resources :all_notices
  
  get 'homes/index'
  
  get 'users/page/:id' => 'users#page'
  
  # User 리스트를 json으로 받아옴.
  get 'users/user_list'
  
  #쪽지
  get '/users/message'
  delete '/users/message/:id' => 'messages#destroy'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  resources :messages, only: [:hide_message] do
    member do
      put "hide_message", to: "messages#hide_message"
      put "hide_message_their", to: "messages#hide_message_their"
    end
  end
  
  #검색 결과
  get 'searches/index' => 'searches#index'
  get 'homes/news_search' => 'homes#news_search'
  
  #알림 : 전체 삭제
  get '/new_notifications/read_all' => 'new_notifications#read_all'
  #알림
  resources :new_notifications
  
  resources :comments, only: [:create, :destroy, :edit, :update] do
    member do
      put "like", to:    "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end
  
  resources :posts
  
  resources :bulletins do
    # 해시태그
    get 'posts/hashtag/:name', to: 'posts#hashtags'
    resources :posts do
      post "/restore", to: "posts#restore"
      member do
        put "like", to:    "posts#upvote"
        put "dislike", to: "posts#downvote"
      end
    end
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/all_notice.rb
class AllNotice < ApplicationRecord
    belongs_to :user
    has_many :impressions, :as=>:impressionable
    
    # cancancan 적용
    resourcify
    
    #게시글이 삭제되도 DB에는 원본 기록이 남아있음.
    acts_as_paranoid
    
    # 게시글 및 댓글 제목, 내용을 다 썼는지 체크
    validates :title, :content, presence: true
    
    # 댓글
    acts_as_commentable
    
    # 조회수
    is_impressionable
 
    def impression_count
        impressions.size
    end
    
    def unique_impression_count
        # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
        # so getting keys from the hash and calculating the number of keys
        impressions.group(:ip_address).size.keys.length #TESTED
    end
end

app/controllers/all_notices_controller.rb
class AllNoticesController < ApplicationController
  # Rolify + Cancancan
  load_and_authorize_resource
  before_action :set_all_notice, only: [:show, :edit, :update, :destroy]
  
  # 조회수
  impressionist actions: [:show], unique: [:ip_address]
  
  # GET /all_notices
  # GET /all_notices.json
  def index
    @all_notices = AllNotice.order("created_at DESC").page(params[:page]).per(10)
  end

  # GET /all_notices/1
  # GET /all_notices/1.json
  def show
    @all_notice   = AllNotice.find(params[:id])
    if user_signed_in?
      @new_comment  = Comment.build_from(@all_notice, current_user.id, "")
    end
  end

  # GET /all_notices/new
  def new
    @all_notice = AllNotice.new
  end

  # GET /all_notices/1/edit
  def edit
  end

  # POST /all_notices
  # POST /all_notices.json
  def create
    @all_notice = AllNotice.new(all_notice_params)

    respond_to do |format|
      if @all_notice.save
        format.html { redirect_to @all_notice, notice: '게시글이 작성되었습니다.' }
        format.json { render :show, status: :created, location: @all_notice }
      else
        format.html { render :new }
        format.json { render json: @all_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /all_notices/1
  # PATCH/PUT /all_notices/1.json
  def update
    respond_to do |format|
      if @all_notice.update(all_notice_params)
        format.html { redirect_to @all_notice, notice: '게시글이 수정되었습니다.' }
        format.json { render :show, status: :ok, location: @all_notice }
      else
        format.html { render :edit }
        format.json { render json: @all_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /all_notices/1
  # DELETE /all_notices/1.json
  def destroy
    @all_notice.destroy
    respond_to do |format|
      format.html { redirect_to all_notices_url, alert: '게시글이 삭제되었습니다.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_all_notice
      @all_notice = AllNotice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def all_notice_params
      params[:all_notice][:user_id] = current_user.id
      params[:all_notice][:user_nickname] = current_user.nickname
      params.require(:all_notice).permit(:title, :content, :user_nickname, :user_id, :allow_comment, :global_notice, :local_notice)
    end
end

app/helpers/all_notices_helper.rb
module AllNoticesHelper
end

app/views/all_notices/_form.html.erb
<%= form_with(model: all_notice, local: true) do |f| %>
  <div class="field" style="margin-top: 30px;">
    <div class="row">
    <div class="col-3 col-sm-2 col-md-1"><%= f.label :"제목" %></div>
    <div class="col-9 col-sm-10 col-md-11"><%= f.text_field :title, class: "input_noborder", autocomplete: "off" %></div>
    </div>
  </div>

  <div class="field" style="margin-top: 10px;">
    <%= tinymce :language => "en" %>
    <%= f.text_area :content, id: :all_notice_content, class: "form-control tinymce", rows: "10" %>
  </div>

  <div class="col-12 col-sm-8 col-md-5" style="background-color: #ffd4d4; margin-top: 30px; margin-bottom: 10px; padding: 10px;"><font color="red"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 어드민 전용 : 게시판 특수기능 설정</font></div>
  <div class="field">
    <%= f.label :global_notice, "모든 게시판 상위공지" %> <%= f.check_box :global_notice, id: :bulletin_global_notice %><br/>
    <%= f.label :local_notice, "공지사항 게시판 상위공지" %> <%= f.check_box :local_notice, id: :bulletin_local_notice %><br/>
    <%= f.label :allow_comment, "댓글 허용" %> <%= f.check_box :allow_comment, id: :bulletin_allow_comment %><br/>
  </div>

  <div align="center" class="actions" style="margin-top: 30px; margin-bottom: 50px;">
    <%= f.submit :"글 쓰기", class: "btn btn-sm btn-primary" %>
    <%= link_to "목록", all_notices_path, class: 'btn btn-sm btn-outline-dark' %>
  </div>
<% end %>

app/views/all_notices/edit.html.erb
<%= render 'all_notices/top_render/top_banner' %>

<%# 경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<%= render 'all_notices/top_render/alert_new&edit', post: @all_notice %>

<div class="container">
    <div class="alert alert-primary" role="alert" style="margin-top: 30px;">
      <i class="fas fa-cogs"></i> 공지사항 수정 중.
    </div>
    
    <%= render 'form', all_notice: @all_notice %>
</div>

app/views/all_notices/index.html.erb
<%= render 'all_notices/top_render/top_banner' %>

<%# 경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<%= render 'all_notices/top_render/alert_normal' %>

<div class="container" style="margin-top: 30px;">
  <div class="row" style="margin-top: 30px;">
    <div class="col-md-7 d-none d-md-block index_board_row" align="center">제목</div>
    <div class="col-md-2 d-none d-md-block index_board_row" align="center">작성날짜</div>
    <div class="col-md-2 d-none d-md-block index_board_row" align="center">닉네임</div>
    <div class="col-md-1 d-none d-md-block index_board_row" align="center">조회수</div>
  </div>
  
  <% if @all_notices.empty? %>
    <h2 class="text-center" style="margin-top: 30px;">게시글이 없습니다.</h2>
  <% else %>
    <%# 모든 게시판 공지 %>
    <% @all_notices.each do |post| %>
      <% if post.global_notice == true %>
        <%= render 'all_notices/index/index_global', post: post %>
      <% end %>
    <% end %>
    
    <%# 공지사항 상위 %>
    <% @all_notices.each do |post| %>
      <% if post.local_notice == true %>
        <%= render 'all_notices/index/index_local', post: post %>
      <% end %>
    <% end %>
    
    <%# 일반 게시물 %>
    <% @all_notices.each do |post| %>
      <%= render 'all_notices/index/index_normal', post: post %>
    <% end %>
  <% end %>
  
  <div align="right" style="margin-top: 30px">
    <div class="d-none d-md-block"><%= render 'searches/search_form_pc', post: @all_notices.klass %></div>
    <div class="d-md-none"><%= render 'searches/search_form_mobile', post: @all_notices.klass %></div>
  </div>
  
  <div style="margin-top: 50px; margin-bottom: 50px;">
    <%= paginate @all_notices %>
  </div>
  
  <% if can? :new, @all_notices %>
    <div align="right"><%= link_to '글 쓰기', new_all_notice_path, class: 'btn btn-sm btn-primary' %></div>
  <% end %>
</div>

app/views/all_notices/new.html.erb
<%= render 'all_notices/top_render/top_banner' %>

<%# 경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<%= render 'all_notices/top_render/alert_new&edit', post: @all_notice %>

<div class="container">
    <%= render 'form', all_notice: @all_notice %>
</div>

app/views/all_notices/show.html.erb
<%= render 'all_notices/top_render/top_banner' %>

<%# 경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<%= render 'all_notices/top_render/alert_normal_with_hide' %>

<div class="container" style="margin-top: 30px;">
  <%= render 'all_notices/show/show_normal', post: @all_notice %>

  <div class="row" style="margin-top: 30px;">
      <div class="col-3 col-sm-4 col-md-3">
          <% if can? :new, @all_notice %>
              <%= link_to '글 쓰기', new_all_notice_path, class: 'btn btn-sm btn-primary' %>
          <% end %>
      </div>
      
      <div align="right" class="col-9 col-sm-8 col-md-9">
          <% if can? :update, @all_notice %>
            <%= link_to '수정', edit_all_notice_path(@all_notice), class: 'btn btn-sm btn-outline-dark' %>
          <% end %>
          
          <% if can? :destroy, @all_notice %>
              <%= link_to '삭제', @all_notice, method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: '정말 게시글을 지우시겠습니까?' } %>
          <% end %>
          <%= link_to '목록', all_notices_path, class: 'btn btn-sm btn-outline-dark' %>
      </div>
  </div>
  <hr/>
  <% if user_signed_in? %>
    <%= render partial: "comments/template", locals: {commentable: @all_notice, new_comment: @comment} %>
  <% else %>

    <div align="center" style="padding: 20px;">
      <h3>
        <i class="far fa-comment-dots" data-toggle="tooltip" data-placement="top" title="댓글 : <%= @all_notice.comment_threads.count %>개"></i>
        <div style="margin-top: 20px">댓글을 달기 위해선 <%= link_to "로그인", new_user_session_path, style: "color: #007cff; text-decoration: none;" %>이 필요합니다.</div>
      </h3>
    </div>
  <% end %>
</div>


<!-- Bootrstrap 4.1 Tooltip 제어 -->
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>
<script src="/bootstrap_4.1/bootstrap.min.js"></script>